FROM node:18-alpine

RUN npm i -g pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .
RUN pnpx prisma generate
RUN pnpm build

CMD ["pnpm", "run", "start:dev"]

EXPOSE 3000