version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./myweb:/usr/share/nginx/html
      - ./certbot-etc:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-log:/var/log/nginx

      # - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      #- ./nginx/templates:/etc/nginx/templates
    #env_file:
    #- ./.env
    #- ./config/.nginx.env

  api_prod:
    image: luckyhyom/barun-api-prod
    tty: true
    restart: always
    command:
      - bash
      - -c
      - |
        pnpm run start:prod
    env_file:
      - ./baruncorp-api/.env

  api_dev:
    image: luckyhyom/barun-api-dev
    tty: true
    restart: always
    command:
      - bash
      - -c
      - |
        pnpm run start:prod
    env_file:
      - ./baruncorp-api-dev/.env

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./myweb:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email gyals0386@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d makevalue.net -d www.makevalue.net
# 도메인 설정, 80포트 443포트 33906포트 열어 놓을 것
