FROM node:18-alpine

RUN npm i -g pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .
RUN pnpm dlx prisma generate
RUN pnpm build

# COPY wait-for-it.sh ./
# RUN chmod +x wait-for-it.sh

CMD ["pnpm", "run", "start:dev"]

EXPOSE 3000