version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

  api_server:
    image: ${API_DOCKER_IMAGE_PATH}
    tty: true
    restart: always
    command:
      - bash
      - -c
      - |
        pnpm run start:prod
    env_file:
      - ./baruncorp-api/.env

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./myweb:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email gyals0386@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d ${API_HOST} -d ${API_WWW_HOST}
    env_file:
      - ./.env.cerbot
# 도메인 설정, 80포트 443포트 33906포트 열어 놓을 것
