version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: always
    ports:
      - '3000:3000'
      - '3001:3001'
    env_file:
      - ./.env
