import { Injectable } from '@nestjs/common'
import { OrderedTasks } from '@prisma/client'
import { Mapper } from '../../libs/ddd/mapper.interface'
import { TaskStatus } from '../ordered-task/domain/ordered-task.type'
import { OrderedTaskEntity } from './domain/ordered-task.entity'

@Injectable()
export class OrderedTaskMapper implements Mapper<OrderedTaskEntity, OrderedTasks, any> {
  toPersistence(entity: OrderedTaskEntity): OrderedTasks {
    const props = entity.getProps()
    return {
      id: entity.id,
      isNewTask: props.isNewTask,
      isLocked: props.isLocked,
      taskStatus: props.taskStatus,
      taskName: props.taskName,
      taskMenuId: props.taskMenuId,
      jobId: props.jobId,
      projectId: props.projectId,
      dateCreated: props.dateCreated,
      assigneeName: props.assigneeName,
      assigneeUserId: props.assigneeUserId,
      description: props.description,
      invoiceAmount: props.invoiceAmount,
      updatedAt: new Date(),
      createdAt: new Date(),

      //#region
      dateAssigned: null,
      dateCompletedCancelled: null,
      notes: null,
      designRevisionScope: null,

      newStorageDesign: null,
      notRequired: null,
      monthlyNewServiceIndexNum: null,
      oldTaskRequestNum: null,
      lineItems: null,
      lineItemsClosed: null,
      agreedContractorFlatPrice: null,
      agreedContractorFlatMajorRevisionPrice: null,
      agreedContractorTaskGroupName: null,
      agreedContractorTaskGroupRevisionPrice: null,
      agreedContractorUnitPrice: null,
      agreedFlatPrice: null,
      agreedFlatMajorRevisionPrice: null,
      agreedRevenueShare: null,
      agreedRevenueShareConditionA: null,
      agreedRevenueShareConditionAPercent: null,
      agreedRevenueShareConditionB: null,
      agreedRevenueShareConditionBPercent: null,
      agreedRevisionRevenueShare: null,
      agreedTaskGroupName: null,
      agreedTaskGroupRevisionPrice: null,
      agreedTier1Price: null,
      agreedTier1MajorRevisionPrice: null,
      agreedTier1Units: null,
      agreedTier2Price: null,
      agreedTier2MajorRevisionPrice: null,
      agreedTier2Units: null,
      agreedTier3Price: null,
      agreedTier3MajorRevisionPrice: null,
      agreedTier3Units: null,
      agreedUnitPrice: null,
      assignedToSnapshot: null,
      calculationTaskAssigneeSummaryContainsTaskAssignee: null,
      combinedLineItemNums: null,
      contactEmail: null,
      contactEmail2: null,
      contactEmailOverride: null,

      contractorUnits: null,
      dateModified: null,
      dateOutsourced: null,
      exportId: null,
      formulaSandbox: null,
      hour: null,
      isActiveContractorSnapshot: null,
      oldIsNewProjectTask: null,
      totalPvDesignActive: null,
      totalPvDesignOnHold: null,
      totalStructuralPeStampActive: null,
      totalStructuralPeStampOnHold: null,
      totalElectricalPeStampActive: null,
      totalElectricalPeStampOnHold: null,
      lastModifiedBy: null,
      projectIndexForElectricalDesign: null,
      projectIndexForElectricalLoadCalculation: null,
      projectIndexForElectricalPeStamp: null,
      projectIndexForElectricalPil: null,
      projectIndexForOther: null,
      projectIndexForStructuralCalculation: null,
      projectIndexForStructuralDesign: null,
      projectIndexForStructuralPeStamp: null,
      projectIndexForStructuralPil: null,
      projectIndexForStructuralPreDesignCheck: null,
      projectIndexForWetStamp: null,
      projectMinimumDateFormula: null,
      recordIdNum: null,
      recordOwner: null,
      relatedInvoiceLineItemDetail: null,
      revenueShareAmount: null,
      taskCountFormula: null,
      taskExpenseOverride: null,
      taskExpenseTotal: null,
      taskPriceOverride: null,
      taskPriceTotal: null,
      taskPriceTotalDiscountTemp: null,
      taskRelatedInvoice: null,
      taskRequestNumOverride: null,
      tier: null,
      tier1Price: null,
      tier2Discount: null,
      tier2Price: null,
      tier3Discount: null,
      tier3Price: null,
      oldTierDiscount: null,
      tieredTaskPrice: null,
      timeCompleted: null,
      triggerLockTask: null,
      triggerOutsource: null,
      unitPriceTask: null,
      units: null,
      isNewTaskOverride: null,
      agreedTier1GroundMountPrice: null,
      agreedTier1GroundMountMajorRevisionPrice: null,
      agreedTier2GroundMountPrice: null,
      agreedTier2GroundMountMajorRevisionPrice: null,
      agreedTier3GroundMountPrice: null,
      agreedTier3GroundMountMajorRevisionPrice: null,
      agreedFlatGroundMountPrice: null,
      agreedFlatGroundMountMajorRevisionPrice: null,
      discount: null,
      formulaSandbox2: null,
      formulaSandbox3: null,
      taskName2: null,
      financialTaskName: null,
      agreedFlatMinorRevisionPrice: null,
      agreedFlatGroundMountMinorRevisionPrice: null,
      agreedTier1MinorRevisionPrice: null,
      agreedTier1GroundMountMinorRevisionPrice: null,
      agreedTier2MinorRevisionPrice: null,
      agreedTier2GroundMountMinorRevisionPrice: null,
      agreedTier3MinorRevisionPrice: null,
      agreedTier3GroundMountMinorRevisionPrice: null,
      agreedNewStorageDesignAdditionalPrice: null,
      isNewStorageDesignTask: null,
      isMajorDesignRevisionTask: null,
      isDesignTask: null,
      isWeekday: null,
      estimatedManHours: null,
      directLaborCosts: null,
      invoicedTaskExpenseTotal: null,
      dateCompletedCancelledReportFormula: null,
      agreedRelatedTaskRevenueShareConditionA: null,
      agreedRelatedTaskRevenueShareConditionB: null,
      contactEmail2Override: null,
      todateDateCompletedCancelledReportFormula: null,
      tier1PriceOverride: null,
      tier2PriceOverride: null,
      tier3PriceOverride: null,
      tier1UnitsOverride: null,
      tier2UnitsOverride: null,
      tier3UnitsOverride: null,
      tier1Units: null,
      tier2Units: null,
      tier3Units: null,
      tieredPricingOverride: null,
      tieredPricing: null,
      relatedTieredUnitDescriptionOverride: null,
      relatedTieredUnitDescription: null,
      taskIndex: null,
      ofExistingBatteriesBeforeThisDesign: null,
      priceOverriddenForMajorTaskPriceFormulaUpdate: null,
      agreedAdditionalOrReplacedStorageDesignAdditionalPrice: null,
      agreedContractorNewStorageDesignAdditionalPrice: null,
      agreedContractorFlatMinorRevisionPrice: null,
      agreedContractorFlatGroundMountPrice: null,
      agreedContractorFlatGroundMountMinorRevisionPrice: null,
      agreedContractorFlatGroundMountMajorRevisionPrice: null,
      agreedContractorAdditionalOrReplacedStorageDesignAdditionalPrice: null,
      taskExpenseFormulaFid38Update2021Dec30: null,
      ofDesignTasksAssigned: null,
      oldestUnassignedTask: null,
      turnaroundTimeHr: null,
      pvDesignMsg: null,
      structuralPeStampMsg: null,
      electricalPeStampMsg: null,
      timeToRun: null,
      ymdCreated: null,
      adminRelatedJob: null,
      auditDateAssignedFix: null,
      auditJobVendorInvoiceMissing: null,
      fixD628: null,
      fix8Bdf: null,
      //#regionend
    }
  }

  toDomain(record: OrderedTasks): OrderedTaskEntity {
    return new OrderedTaskEntity({
      id: record.id,
      props: {
        invoiceAmount: record.invoiceAmount,
        isNewTask: record.isNewTask,
        isLocked: record.isLocked,
        taskStatus: record.taskStatus as TaskStatus,
        taskName: record.taskName,
        taskMenuId: record.taskMenuId,
        jobId: record.jobId,
        projectId: record.projectId,
        dateCreated: record.dateCreated,
        assigneeName: record.assigneeName,
        assigneeUserId: record.assigneeUserId,
        description: record.description,
      },
    })
  }

  toResponse(entity: OrderedTaskEntity, ...dtos: any): any {
    // throw new Error('Method not implemented.')
  }
}
