FROM nginx:alpine

# Install logrotate
RUN apk add --no-cache logrotate

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./logrotate.conf /etc/logrotate.conf

COPY ./script.sh /script.sh
RUN chmod +x /script.sh

ENTRYPOINT ["/script.sh"]