import { AHJNotesModel } from '../database/geography.repository'

export type UpdateNoteType = Partial<
  Pick<
    AHJNotesModel,
    | 'website'
    | 'specificFormRequired'
    | 'generalNotes'
    | 'buildingCodes'
    | 'fireSetBack'
    | 'utilityNotes'
    | 'designNotes'
    | 'pvMeterRequired'
    | 'acDisconnectRequired'
    | 'centerFed120Percent'
    | 'deratedAmpacity'
    | 'engineeringNotes'
    | 'iebcAccepted'
    | 'structuralObservationRequired'
    | 'windUpliftCalculationRequired'
    | 'wetStampsRequired'
    | 'digitalSignatureType'
    | 'windExposure'
    | 'wetStampSize'
    | 'windSpeed'
    | 'snowLoadGround'
    | 'snowLoadFlatRoof'
    | 'snowLoadSlopedRoof'
    | 'ofWetStamps'
    | 'electricalNotes'
    | 'generalNotes'
    | 'utilityNotes'
    | 'designNotes'
    | 'engineeringNotes'
    | 'electricalNotes'
  >
>
